### PR TITLE
webpack skeleton setup

### PR DESCRIPTION
**Pull request by v-za**

### CODE REVIEW

**Comment by vickiwyang** [comment]
Awesome!

**Comment by allisonIsCoding** [comment]
Looks good to me! Well done Vinit!

**Comment by akikoinhd** [comment]
Very nice, Vinit.

**Review by akikoinhd — APPROVED** [review]

**Review by allisonIsCoding — CHANGES_REQUESTED** [review]
Looks great - thanks Vinit!

**Review by allisonIsCoding — APPROVED** [review]

**Pull request merged**
